use keyboard_types::{Code, Key, KeyState, Location, Modifiers, NamedKey};

pub fn macos_hid_to_code(usage: usize) -> Code {
    match usage {
        // Letters
        0x04 => Code::KeyA,
        0x05 => Code::KeyB,
        0x06 => Code::KeyC,
        0x07 => Code::KeyD,
        0x08 => Code::KeyE,
        0x09 => Code::KeyF,
        0x0A => Code::KeyG,
        0x0B => Code::KeyH,
        0x0C => Code::KeyI,
        0x0D => Code::KeyJ,
        0x0E => Code::KeyK,
        0x0F => Code::KeyL,
        0x10 => Code::KeyM,
        0x11 => Code::KeyN,
        0x12 => Code::KeyO,
        0x13 => Code::KeyP,
        0x14 => Code::KeyQ,
        0x15 => Code::KeyR,
        0x16 => Code::KeyS,
        0x17 => Code::KeyT,
        0x18 => Code::KeyU,
        0x19 => Code::KeyV,
        0x1A => Code::KeyW,
        0x1B => Code::KeyX,
        0x1C => Code::KeyY,
        0x1D => Code::KeyZ,
        // Number row
        0x1E => Code::Digit1,
        0x1F => Code::Digit2,
        0x20 => Code::Digit3,
        0x21 => Code::Digit4,
        0x22 => Code::Digit5,
        0x23 => Code::Digit6,
        0x24 => Code::Digit7,
        0x25 => Code::Digit8,
        0x26 => Code::Digit9,
        0x27 => Code::Digit0,
        // Control keys
        0x28 => Code::Enter,
        0x29 => Code::Escape,
        0x2A => Code::Backspace,
        0x2B => Code::Tab,
        0x2C => Code::Space,
        // Symbols
        0x2D => Code::Minus,
        0x2E => Code::Equal,
        0x2F => Code::BracketLeft,
        0x30 => Code::BracketRight,
        0x31 => Code::Backslash,
        0x32 => Code::IntlBackslash,
        0x33 => Code::Semicolon,
        0x34 => Code::Quote,
        0x35 => Code::Backquote,
        0x36 => Code::Comma,
        0x37 => Code::Period,
        0x38 => Code::Slash,
        // Lock keys
        0x39 => Code::CapsLock,
        // Function keys
        0x3A => Code::F1,
        0x3B => Code::F2,
        0x3C => Code::F3,
        0x3D => Code::F4,
        0x3E => Code::F5,
        0x3F => Code::F6,
        0x40 => Code::F7,
        0x41 => Code::F8,
        0x42 => Code::F9,
        0x43 => Code::F10,
        0x44 => Code::F11,
        0x45 => Code::F12,
        // Navigation cluster
        0x46 => Code::PrintScreen,
        0x47 => Code::ScrollLock,
        0x48 => Code::Pause,
        0x49 => Code::Insert,
        0x4A => Code::Home,
        0x4B => Code::PageUp,
        0x4C => Code::Delete,
        0x4D => Code::End,
        0x4E => Code::PageDown,
        // Arrow keys
        0x4F => Code::ArrowRight,
        0x50 => Code::ArrowLeft,
        0x51 => Code::ArrowDown,
        0x52 => Code::ArrowUp,
        // Numpad
        0x53 => Code::NumLock,
        0x54 => Code::NumpadDivide,
        0x55 => Code::NumpadMultiply,
        0x56 => Code::NumpadSubtract,
        0x57 => Code::NumpadAdd,
        0x58 => Code::NumpadEnter,
        0x59 => Code::Numpad1,
        0x5A => Code::Numpad2,
        0x5B => Code::Numpad3,
        0x5C => Code::Numpad4,
        0x5D => Code::Numpad5,
        0x5E => Code::Numpad6,
        0x5F => Code::Numpad7,
        0x60 => Code::Numpad8,
        0x61 => Code::Numpad9,
        0x62 => Code::Numpad0,
        0x63 => Code::NumpadDecimal,
        // Extended function keys
        0x68 => Code::F13,
        0x69 => Code::F14,
        0x6A => Code::F15,
        0x6B => Code::F16,
        0x6C => Code::F17,
        0x6D => Code::F18,
        0x6E => Code::F19,
        0x6F => Code::F20,
        0x70 => Code::F21,
        0x71 => Code::F22,
        0x72 => Code::F23,
        0x73 => Code::F24,
        // Modifiers
        0xE0 => Code::ControlLeft,
        0xE1 => Code::ShiftLeft,
        0xE2 => Code::AltLeft,
        0xE3 => Code::MetaLeft,
        0xE4 => Code::ControlRight,
        0xE5 => Code::ShiftRight,
        0xE6 => Code::AltRight,
        0xE7 => Code::MetaRight,
        _ => Code::Unidentified,
    }
}

pub fn macos_hid_to_key(usage: usize) -> Key {
    let named_key = match usage {
        0x29 => Some(NamedKey::Escape),
        0x28 | 0x58 => Some(NamedKey::Enter),
        0x2B => Some(NamedKey::Tab),
        0x2A => Some(NamedKey::Backspace),
        0x4C => Some(NamedKey::Delete),
        0x49 => Some(NamedKey::Insert),
        0x4A => Some(NamedKey::Home),
        0x4D => Some(NamedKey::End),
        0x4B => Some(NamedKey::PageUp),
        0x4E => Some(NamedKey::PageDown),
        0x52 => Some(NamedKey::ArrowUp),
        0x51 => Some(NamedKey::ArrowDown),
        0x50 => Some(NamedKey::ArrowLeft),
        0x4F => Some(NamedKey::ArrowRight),
        0x39 => Some(NamedKey::CapsLock),
        0x53 => Some(NamedKey::NumLock),
        0x47 => Some(NamedKey::ScrollLock),
        0xE0 | 0xE4 => Some(NamedKey::Control),
        0xE1 | 0xE5 => Some(NamedKey::Shift),
        0xE2 | 0xE6 => Some(NamedKey::Alt),
        0xE3 | 0xE7 => Some(NamedKey::Meta),
        0x46 => Some(NamedKey::PrintScreen),
        0x48 => Some(NamedKey::Pause),
        0x3A => Some(NamedKey::F1),
        0x3B => Some(NamedKey::F2),
        0x3C => Some(NamedKey::F3),
        0x3D => Some(NamedKey::F4),
        0x3E => Some(NamedKey::F5),
        0x3F => Some(NamedKey::F6),
        0x40 => Some(NamedKey::F7),
        0x41 => Some(NamedKey::F8),
        0x42 => Some(NamedKey::F9),
        0x43 => Some(NamedKey::F10),
        0x44 => Some(NamedKey::F11),
        0x45 => Some(NamedKey::F12),
        0x68 => Some(NamedKey::F13),
        0x69 => Some(NamedKey::F14),
        0x6A => Some(NamedKey::F15),
        0x6B => Some(NamedKey::F16),
        0x6C => Some(NamedKey::F17),
        0x6D => Some(NamedKey::F18),
        0x6E => Some(NamedKey::F19),
        0x6F => Some(NamedKey::F20),
        0x70 => Some(NamedKey::F21),
        0x71 => Some(NamedKey::F22),
        0x72 => Some(NamedKey::F23),
        0x73 => Some(NamedKey::F24),
        _ => None,
    };
    match named_key {
        Some(key) => Key::Named(key),
        None => Key::Named(NamedKey::Unidentified),
    }
}

pub fn macos_hid_to_location(usage: usize) -> Location {
    match usage {
        0xE0 | 0xE1 | 0xE2 | 0xE3 => Location::Left,
        0xE4 | 0xE5 | 0xE6 | 0xE7 => Location::Right,
        0x53..=0x63 => Location::Numpad,
        _ => Location::Standard,
    }
}

pub fn modifier_for_usage(usage: usize) -> Option<Modifiers> {
    match usage {
        0xE1 | 0xE5 => Some(Modifiers::SHIFT),
        0xE0 | 0xE4 => Some(Modifiers::CONTROL),
        0xE2 => Some(Modifiers::ALT),
        0xE6 => Some(Modifiers::ALT_GRAPH),
        0xE3 | 0xE7 => Some(Modifiers::META),
        0x39 => Some(Modifiers::CAPS_LOCK),
        0x53 => Some(Modifiers::NUM_LOCK),
        0x47 => Some(Modifiers::SCROLL_LOCK),
        _ => None,
    }
}

pub fn macos_value_to_key_state(value: isize) -> Option<(KeyState, bool)> {
    match value {
        0 => Some((KeyState::Up, false)),
        1 => Some((KeyState::Down, false)),
        _ => None,
    }
}
